import os
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def _send_via_smtp(to_emails, subject, body):
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    from_email = os.getenv("SMTP_FROM", "pr-reviewer@example.com")

    if not all([smtp_host, smtp_user, smtp_pass]):
        print("SMTP not configured. Skipping email.")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_email
    msg["To"] = ", ".join(to_emails)
    msg.attach(MIMEText(body, "plain"))

    ctx = ssl.create_default_context()
    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls(context=ctx)
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_email, to_emails, msg.as_string())
        print(f"Email sent to {len(to_emails)} recipient(s) via SMTP.")
        return True
    except smtplib.SMTPException as e:
        print(f"SMTP error: {e}")
        return False


def _build_email_body(repo_name, pr_number, summary, findings_count):
    pr_url = f"https://github.com/{repo_name}/pull/{pr_number}"
    return f"""
PR Review: {repo_name}#{pr_number}
PR URL: {pr_url}

{summary}

---
{findings_count} finding(s) identified.
Review generated by AI PR Reviewer Agent.
"""


def send_email_notification(repo_name, pr_number, recipients, summary, findings_count):
    if not recipients:
        print("No email recipients. Skipping notification.")
        return False

    subject = f"[PR Review] {repo_name}#{pr_number} — {findings_count} finding(s)"
    body = _build_email_body(repo_name, pr_number, summary, findings_count)
    return _send_via_smtp(recipients, subject, body)
