KB_VERSION = 1

CODE_REVIEW_BAD_PRACTICES = [
    {
        "id": "CR-001",
        "title": "Hardcoded secrets",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 1,
        "description": "Hardcoded API keys, passwords, tokens, or other credentials in source code.",
        "bad_pattern": "API_KEY = 'sk-1234567890abcdef'",
        "good_pattern": "API_KEY = os.getenv('API_KEY')",
        "suggested_fix": "Use environment variables or a secrets manager.",
        "keywords": ["api_key", "password", "secret", "token", "credential", "sk-", "AKIA"],
    },
    {
        "id": "CR-002",
        "title": "SQL injection via string formatting",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 2,
        "description": "Building SQL queries with string formatting or concatenation using user input.",
        "bad_pattern": "cursor.execute(f'SELECT * FROM users WHERE id={user_id}')",
        "good_pattern": "cursor.execute('SELECT * FROM users WHERE id=?', (user_id,))",
        "suggested_fix": "Use parameterized queries or an ORM.",
        "keywords": ["execute", "SELECT", "INSERT", "DELETE", "UPDATE", "f'", "format("],
    },
    {
        "id": "CR-003",
        "title": "Command injection",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 3,
        "description": "Passing unsanitized user input to shell commands or subprocess calls.",
        "bad_pattern": "subprocess.run(f'grep {user_input} /var/log/syslog', shell=True)",
        "good_pattern": "subprocess.run(['grep', user_input, '/var/log/syslog'], check=True)",
        "suggested_fix": "Avoid shell=True and pass arguments as a list, or sanitize input strictly.",
        "keywords": ["subprocess", "os.system", "shell=True", "popen", "exec", "eval"],
    },
    {
        "id": "CR-004",
        "title": "Path traversal",
        "version": 1,
        "severity": "HIGH",
        "popularity": 4,
        "description": "Using user-provided filenames without validation, allowing access to files outside intended directory.",
        "bad_pattern": "with open(f'/var/data/{filename}', 'r') as f:",
        "good_pattern": "safe_path = os.path.abspath(os.path.join('/var/data/', filename))\nif not safe_path.startswith('/var/data/'): raise ValueError()",
        "suggested_fix": "Validate and sanitize file paths; use os.path.abspath and check prefix.",
        "keywords": ["open(", "file", "path", "upload", "download", "os.path"],
    },
    {
        "id": "CR-005",
        "title": "Use of eval / exec on user input",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 5,
        "description": "Using eval(), exec(), or similar dynamic code execution with untrusted input.",
        "bad_pattern": "result = eval(user_input)",
        "good_pattern": "Avoid eval/exec entirely. Use safer alternatives like ast.literal_eval for parsing.",
        "suggested_fix": "Replace eval/exec with type-specific parsers.",
        "keywords": ["eval(", "exec(", "__import__", "compile("],
    },
    {
        "id": "CR-006",
        "title": "Insecure deserialization",
        "version": 1,
        "severity": "HIGH",
        "popularity": 6,
        "description": "Deserializing data from untrusted sources using pickle, yaml.load, or similar.",
        "bad_pattern": "data = pickle.loads(untrusted_data)",
        "good_pattern": "Use json.loads for trusted data; avoid pickle with untrusted sources.",
        "suggested_fix": "Use safe serialization formats like JSON. If pickle is required, verify integrity with HMAC.",
        "keywords": ["pickle", "yaml.load", "yaml_load", "deserialize", "unserialize"],
    },
    {
        "id": "CR-007",
        "title": "Cross-Site Scripting (XSS)",
        "version": 1,
        "severity": "HIGH",
        "popularity": 7,
        "description": "Rendering user input directly in HTML/JS without sanitization.",
        "bad_pattern": "element.innerHTML = user_input",
        "good_pattern": "element.textContent = user_input",
        "suggested_fix": "Use textContent instead of innerHTML, or sanitize with DOMPurify.",
        "keywords": ["innerHTML", "outerHTML", "dangerouslySetInnerHTML", "v-html"],
    },
    {
        "id": "CR-008",
        "title": "Insecure direct object reference (IDOR)",
        "version": 1,
        "severity": "HIGH",
        "popularity": 8,
        "description": "Exposing internal object references (e.g., database IDs) without authorization checks.",
        "bad_pattern": "@app.route('/api/user/<int:user_id>')\ndef get_user(user_id):\n    return db.query(User, user_id)",
        "good_pattern": "Check that the authenticated user has access to the requested resource.",
        "suggested_fix": "Always verify ownership/authorization before returning resource data.",
        "keywords": ["user_id", "authorization", "permission", "access control", "bypass"],
    },
    {
        "id": "CR-009",
        "title": "Missing input validation",
        "version": 1,
        "severity": "HIGH",
        "popularity": 9,
        "description": "Accepting user input without validating type, length, range, or format.",
        "bad_pattern": "age = int(request.form['age'])",
        "good_pattern": "if not 0 < int(age) < 150: raise ValidationError()",
        "suggested_fix": "Validate all input: type, length, range, format, and reject unexpected values.",
        "keywords": ["request", "input", "form", "query", "param", "validate"],
    },
    {
        "id": "CR-010",
        "title": "Hardcoded configuration / magic numbers",
        "version": 1,
        "severity": "LOW",
        "popularity": 10,
        "description": "Using literal values, magic numbers, or inline configuration instead of constants or config files.",
        "bad_pattern": "timeout = 30  # connection timeout",
        "good_pattern": "CONNECTION_TIMEOUT = 30  # defined as a constant at module level",
        "suggested_fix": "Extract magic values into named constants or configuration variables.",
        "keywords": ["magic", "literal", "hardcode", "inline", "constant"],
    },
    {
        "id": "CR-011",
        "title": "Missing error handling",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 11,
        "description": "Bare except clauses or swallowing exceptions without logging or handling.",
        "bad_pattern": "try:\n    process(data)\nexcept:\n    pass",
        "good_pattern": "try:\n    process(data)\nexcept SpecificError as e:\n    logger.error('Failed: %s', e)\n    raise",
        "suggested_fix": "Catch specific exceptions, log appropriately, and fail gracefully.",
        "keywords": ["except:", "except Exception", "pass", "try:", "bare except"],
    },
    {
        "id": "CR-012",
        "title": "Logging sensitive data",
        "version": 1,
        "severity": "HIGH",
        "popularity": 12,
        "description": "Logging passwords, tokens, PII, or other sensitive information.",
        "bad_pattern": "logger.info('User login: %s %s', username, password)",
        "good_pattern": "logger.info('User login attempt: %s', username)",
        "suggested_fix": "Never log secrets. Mask or omit sensitive fields before logging.",
        "keywords": ["logger", "print(", "log("],
    },
    {
        "id": "CR-013",
        "title": "Race condition (TOCTOU)",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 13,
        "description": "Time-of-check to time-of-use vulnerability where a resource changes between check and use.",
        "bad_pattern": "if os.path.exists(f): os.remove(f)",
        "good_pattern": "try:\n    os.remove(f)\nexcept FileNotFoundError:\n    pass",
        "suggested_fix": "Use atomic operations, locks, or exception-based handling instead of check-then-act.",
        "keywords": ["os.path.exists", "os.access", "file", "lock", "thread"],
    },
    {
        "id": "CR-014",
        "title": "Hardcoded IP addresses / domains",
        "version": 1,
        "severity": "LOW",
        "popularity": 14,
        "description": "Hardcoding IP addresses or domain names instead of using configuration or DNS.",
        "bad_pattern": "host = '192.168.1.100'",
        "good_pattern": "host = os.getenv('DB_HOST', 'localhost')",
        "suggested_fix": "Move network addresses to environment variables or config files.",
        "keywords": ["http://", "https://", "tcp://", "connect(", "host"],
    },
    {
        "id": "CR-015",
        "title": "Missing rate limiting / brute force protection",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 15,
        "description": "Authentication endpoints without rate limiting or account lockout.",
        "bad_pattern": "@app.route('/login', methods=['POST'])\ndef login():\n    ...",
        "good_pattern": "Add rate limiting middleware (e.g., flask-limiter) to auth endpoints.",
        "suggested_fix": "Implement rate limiting, account lockout, and CAPTCHA on auth endpoints.",
        "keywords": ["login", "password", "auth", "authenticate", "signin"],
    },
    {
        "id": "CR-016",
        "title": "SQL injection via raw queries",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 16,
        "description": "Using raw SQL queries with string concatenation instead of an ORM or parameterized queries.",
        "bad_pattern": "db.execute(f'SELECT * FROM items WHERE cat={category_id}')",
        "good_pattern": "db.execute('SELECT * FROM items WHERE cat=?', (category_id,))",
        "suggested_fix": "Use an ORM or parameterized queries consistently.",
        "keywords": ["raw", "native query", "entityManager", "db.execute"],
    },
    {
        "id": "CR-017",
        "title": "Setting overly permissive CORS",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 17,
        "description": "Allowing any origin in CORS headers, which exposes the API to cross-origin attacks.",
        "bad_pattern": "Access-Control-Allow-Origin: *",
        "good_pattern": "Access-Control-Allow-Origin: https://trusted-frontend.com",
        "suggested_fix": "Restrict CORS to specific trusted origins instead of wildcard.",
        "keywords": ["cors", "Access-Control-Allow-Origin", "cross-origin"],
    },
    {
        "id": "CR-018",
        "title": "Memory leak / unclosed resources",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 18,
        "description": "Opening files, connections, or streams without closing them or using context managers.",
        "bad_pattern": "f = open('file.txt', 'r')\ndata = f.read()",
        "good_pattern": "with open('file.txt', 'r') as f:\n    data = f.read()",
        "suggested_fix": "Use context managers (with statements) for all resources.",
        "keywords": ["open(", "file", "connection", "socket", "stream"],
    },
    {
        "id": "CR-019",
        "title": "Insufficient logging / monitoring",
        "version": 1,
        "severity": "LOW",
        "popularity": 19,
        "description": "Critical operations (auth, payment, data deletion) not logged for audit trail.",
        "bad_pattern": "def delete_user(id): db.execute('DELETE FROM users WHERE id=?', id)",
        "good_pattern": "def delete_user(id):\n    logger.info('User deleted: %s by %s', id, current_user)\n    db.execute('DELETE FROM users WHERE id=?', id)",
        "suggested_fix": "Add structured logging for all security-relevant operations.",
        "keywords": ["delete", "update", "insert", "payment", "charge"],
    },
    {
        "id": "CR-020",
        "title": "Using deprecated / unsafe functions",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 20,
        "description": "Using deprecated or known-unsafe functions like md5, sha1, random, unsafe_compare, etc.",
        "bad_pattern": "hash = md5(password.encode())",
        "good_pattern": "hash = hashlib.sha256(password.encode()).hexdigest()",
        "suggested_fix": "Replace with modern, safe alternatives (sha256/bcrypt for hashing, secrets for crypto).",
        "keywords": ["md5", "sha1", "random", "mt_rand", "strcpy", "gets"],
    },
]
