KB_VERSION = 1

SECURITY_BAD_PRACTICES = [
    {
        "id": "SEC-001",
        "title": "SQL injection via string interpolation",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 1,
        "description": "User input concatenated directly into SQL queries enables attackers to manipulate query logic.",
        "bad_pattern": "query = f'SELECT * FROM users WHERE email = \\'{email}\\''",
        "good_pattern": "query = 'SELECT * FROM users WHERE email = ?'\ncursor.execute(query, (email,))",
        "suggested_fix": "Always use parameterized queries or prepared statements.",
        "keywords": ["execute", "SELECT", "INSERT", "UPDATE", "DELETE", "f'", "format(", "%s"],
    },
    {
        "id": "SEC-002",
        "title": "OS command injection",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 2,
        "description": "Passing unvalidated user input to shell commands allows arbitrary command execution.",
        "bad_pattern": "os.system(f'ping {hostname}')",
        "good_pattern": "subprocess.run(['ping', hostname], check=True)  # no shell=True",
        "suggested_fix": "Avoid shell=True and pass arguments as a list. Validate input against a whitelist.",
        "keywords": ["os.system", "subprocess", "shell=True", "popen", "exec", "`", "$("],
    },
    {
        "id": "SEC-003",
        "title": "Hardcoded cryptographic keys / secrets",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 3,
        "description": "Secrets committed to version control are exposed to anyone with repo access and compromise all environments.",
        "bad_pattern": "JWT_SECRET = 'my-super-secret-key-12345'",
        "good_pattern": "JWT_SECRET = os.environ['JWT_SECRET']",
        "suggested_fix": "Store secrets in environment variables, vaults (HashiCorp Vault), or cloud secret managers.",
        "keywords": ["secret", "key", "password", "token", "credential", "sk-", "AKIA"],
    },
    {
        "id": "SEC-004",
        "title": "Path traversal in file operations",
        "version": 1,
        "severity": "HIGH",
        "popularity": 4,
        "description": "User-controlled filenames without sanitization let attackers read/write files outside the intended directory.",
        "bad_pattern": "with open(os.path.join(UPLOAD_DIR, filename), 'rb') as f:",
        "good_pattern": "safe = os.path.abspath(os.path.join(UPLOAD_DIR, filename))\nif not safe.startswith(UPLOAD_DIR): raise PermissionError",
        "suggested_fix": "Normalize the path, resolve symlinks, and verify it stays within the allowed directory.",
        "keywords": ["open(", "file", "path", "upload", "download", "../", "..\\\\"],
    },
    {
        "id": "SEC-005",
        "title": "Insecure deserialization (pickle/yaml)",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 5,
        "description": "Deserializing untrusted data can lead to RCE via crafted payloads in pickle, YAML, or similar formats.",
        "bad_pattern": "data = yaml.load(user_input)",
        "good_pattern": "data = yaml.safe_load(user_input)",
        "suggested_fix": "Never use pickle with untrusted data. Use safe_load for YAML. Prefer JSON for untrusted sources.",
        "keywords": ["pickle", "yaml.load", "yaml_load", "marshal", "deserialize"],
    },
    {
        "id": "SEC-006",
        "title": "Cross-Site Scripting (XSS) in templates",
        "version": 1,
        "severity": "HIGH",
        "popularity": 6,
        "description": "Rendering unsanitized user input in HTML contexts enables script injection.",
        "bad_pattern": "<div>{{ user_input | safe }}</div>",
        "good_pattern": "<div>{{ user_input }}</div>  <!-- auto-escaped by most template engines -->",
        "suggested_fix": "Avoid marking content as safe unless it is trusted and sanitized. Use autoescaping.",
        "keywords": ["| safe", "innerHTML", "dangerouslySetInnerHTML", "v-html", "raw"],
    },
    {
        "id": "SEC-007",
        "title": "Weak password hashing (MD5/SHA1/unsalted)",
        "version": 1,
        "severity": "HIGH",
        "popularity": 7,
        "description": "Using fast hash functions or unsalted hashes for passwords makes brute-force and rainbow-table attacks feasible.",
        "bad_pattern": "hashed = hashlib.md5(password.encode()).hexdigest()",
        "good_pattern": "hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())",
        "suggested_fix": "Use bcrypt, scrypt, Argon2, or PBKDF2 with a work factor and salt.",
        "keywords": ["md5(", "sha1(", "hash(", "password", "bcrypt", "hashlib"],
    },
    {
        "id": "SEC-008",
        "title": "Missing authentication / authorization checks",
        "version": 1,
        "severity": "CRITICAL",
        "popularity": 8,
        "description": "API endpoints or functions accessible without verifying the user's identity or permissions.",
        "bad_pattern": "@app.route('/admin/delete_user')\ndef delete_user(user_id):\n    db.execute('DELETE FROM users WHERE id=?', user_id)",
        "good_pattern": "@app.route('/admin/delete_user')\n@login_required\n@admin_required\ndef delete_user(user_id): ...",
        "suggested_fix": "Add decorators or middleware for authentication and authorization on all protected routes.",
        "keywords": ["route", "endpoint", "api", "delete", "admin", "authenticate"],
    },
    {
        "id": "SEC-009",
        "title": "Server-Side Request Forgery (SSRF)",
        "version": 1,
        "severity": "HIGH",
        "popularity": 9,
        "description": "Allowing user-controlled URLs in server-side requests can be used to probe internal networks.",
        "bad_pattern": "resp = requests.get(user_url)",
        "good_pattern": "parsed = urlparse(user_url)\nif parsed.hostname not in ALLOWED_DOMAINS: raise ValueError()\nresp = requests.get(user_url)",
        "suggested_fix": "Whitelist allowed domains/IPs. Block private IP ranges and loopback addresses.",
        "keywords": ["requests.get", "requests.post", "fetch(", "curl", "urlopen"],
    },
    {
        "id": "SEC-010",
        "title": "Broken access control / IDOR",
        "version": 1,
        "severity": "HIGH",
        "popularity": 10,
        "description": "Exposing direct references (e.g., numeric IDs) without verifying the user owns the resource.",
        "bad_pattern": "def get_invoice(invoice_id):\n    return db.query(Invoice, invoice_id)",
        "good_pattern": "def get_invoice(invoice_id):\n    invoice = db.query(Invoice, invoice_id)\n    if invoice.user_id != current_user.id: raise Forbidden\n    return invoice",
        "suggested_fix": "Always verify resource ownership before returning data. Use opaque identifiers where possible.",
        "keywords": ["user_id", "invoice_id", "account_id", "ownership", "authorization"],
    },
    {
        "id": "SEC-011",
        "title": "Insufficient CSRF protection",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 11,
        "description": "State-changing endpoints without CSRF tokens allow cross-site request forgery.",
        "bad_pattern": "@app.route('/transfer', methods=['POST'])\ndef transfer():\n    ...",
        "good_pattern": "@app.route('/transfer', methods=['POST'])\n@csrf.protect\ndef transfer():\n    ...",
        "suggested_fix": "Use CSRF tokens for all state-changing POST/PUT/DELETE endpoints.",
        "keywords": ["POST", "PUT", "DELETE", "csrf", "form", "submit"],
    },
    {
        "id": "SEC-012",
        "title": "Insecure cryptographic algorithm or key size",
        "version": 1,
        "severity": "HIGH",
        "popularity": 12,
        "description": "Using deprecated ciphers (DES, RC4), small key sizes (RSA < 2048), or ECB mode leaks pattern info.",
        "bad_pattern": "cipher = DES.new(key, DES.MODE_ECB)",
        "good_pattern": "cipher = AES.new(key, AES.MODE_GCM)",
        "suggested_fix": "Use AES-256-GCM, ChaCha20-Poly1305, or RSA-2048+. Avoid ECB mode.",
        "keywords": ["DES", "RC4", "ECB", "RSA", "AES", "cipher", "encrypt"],
    },
    {
        "id": "SEC-013",
        "title": "Exposed debug / info endpoints in production",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 13,
        "description": "Debug endpoints, stack traces, or verbose error messages leak implementation details.",
        "bad_pattern": "app.run(debug=True)",
        "good_pattern": "if __name__ == '__main__':\n    app.run(debug=os.getenv('DEBUG', 'false').lower() == 'true')",
        "suggested_fix": "Disable debug mode in production. Return generic error messages to users.",
        "keywords": ["debug", "traceback", "stack trace", "exception", "/debug"],
    },
    {
        "id": "SEC-014",
        "title": "No rate limiting on auth endpoints",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 14,
        "description": "Login/signup endpoints without rate limiting enable brute-force password guessing.",
        "bad_pattern": "@app.route('/login', methods=['POST'])\ndef login():\n    ...",
        "good_pattern": "@app.route('/login', methods=['POST'])\n@limiter.limit('5 per minute')\ndef login():\n    ...",
        "suggested_fix": "Apply rate limiting (e.g., 5 attempts/minute) and account lockout after N failures.",
        "keywords": ["login", "signin", "authenticate", "password", "brute", "rate limit"],
    },
    {
        "id": "SEC-015",
        "title": "Logging or exposing PII",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 15,
        "description": "Logging email, phone, SSN, or other PII violates compliance (GDPR, CCPA, HIPAA).",
        "bad_pattern": "logger.info('User registered: %s', user.email)",
        "good_pattern": "logger.info('User registered: %s (ID: %s)', user.username[:1] + '***', user.id)",
        "suggested_fix": "Mask, truncate, or omit PII fields before logging. Use structured logging with PII tagging.",
        "keywords": ["email", "phone", "ssn", "credit", "address", "pii", "gdpr"],
    },
    {
        "id": "SEC-016",
        "title": "Weak session management",
        "version": 1,
        "severity": "HIGH",
        "popularity": 16,
        "description": "Predictable session tokens, missing secure/HttpOnly flags, or long session lifetimes.",
        "bad_pattern": "response.set_cookie('session_id', str(user.id))",
        "good_pattern": "response.set_cookie('session_id', secrets.token_urlsafe(32), httponly=True, secure=True, samesite='Strict')",
        "suggested_fix": "Use cryptographically random session IDs. Set HttpOnly, Secure, SameSite flags. Short expiry.",
        "keywords": ["session", "cookie", "set_cookie", "token", "jwt"],
    },
    {
        "id": "SEC-017",
        "title": "Missing Content Security Policy (CSP)",
        "version": 1,
        "severity": "LOW",
        "popularity": 17,
        "description": "No CSP headers allow inline scripts and external script injection.",
        "bad_pattern": "response.headers['Content-Security-Policy'] = ''",
        "good_pattern": "response.headers['Content-Security-Policy'] = \"default-src 'self'; script-src 'self'\"",
        "suggested_fix": "Add a strict CSP header. Start with report-only mode and gradually tighten.",
        "keywords": ["Content-Security-Policy", "csp", "script-src", "inline script"],
    },
    {
        "id": "SEC-018",
        "title": "Open redirect",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 18,
        "description": "Redirecting to user-controlled URLs without validation enables phishing attacks.",
        "bad_pattern": "redirect(request.args.get('next'))",
        "good_pattern": "ALLOWED_REDIRECTS = {'/dashboard', '/profile'}\nif next_url not in ALLOWED_REDIRECTS: next_url = '/'",
        "suggested_fix": "Whitelist allowed redirect destinations. Avoid using user input as redirect target.",
        "keywords": ["redirect", "next", "return_url", "redirect_uri"],
    },
    {
        "id": "SEC-019",
        "title": "Prototype pollution (JavaScript)",
        "version": 1,
        "severity": "HIGH",
        "popularity": 19,
        "description": "Merging user-controlled objects into existing objects can pollute Object.prototype.",
        "bad_pattern": "Object.assign(target, user_input)",
        "good_pattern": "const clean = JSON.parse(JSON.stringify(user_input))\nObject.assign(target, clean)",
        "suggested_fix": "Avoid recursive merge on untrusted objects. Use Object.create(null) for maps.",
        "keywords": ["Object.assign", "merge", "spread", "__proto__", "constructor"],
    },
    {
        "id": "SEC-020",
        "title": "Insufficient TLS / HTTPS enforcement",
        "version": 1,
        "severity": "MEDIUM",
        "popularity": 20,
        "description": "Allowing HTTP connections or missing HSTS headers enables man-in-the-middle attacks.",
        "bad_pattern": "app.run(ssl_context=None)",
        "good_pattern": "Use a reverse proxy (nginx/Caddy) that enforces HTTPS and sets Strict-Transport-Security.",
        "suggested_fix": "Redirect HTTP to HTTPS. Set Strict-Transport-Security header with a long max-age.",
        "keywords": ["http://", "ssl", "tls", "https", "hsts"],
    },
]
